### ISSUE TITLE
Create script for prompting Llama 7b, BloomZ and Mistral 7b

### ISSUE THREAD

**Issue by owos** [owos/afri_augs#2]
Solution should provide a script for prompt llama 7b with a given template prompt. The script should take in CLI arguments and be transferable to other models like Mistral and bloomz. See [[2307.16833] Data Augmentation for Neural Machine Translation using Generative Language Model](https://arxiv.org/abs/2307.16833) for more information.

Useful resources:
https://github.com/zsc/llama_infer/blob/main

**Comment by faithhunja** [comment]
Hello. 
I am interested in this issue. Could I have it assigned to me?
Thanks.

**Comment by faithhunja** [comment]
Hi @owos .
Will post some code later today for your review
