### ISSUE TITLE
Create a script to perform Sentence Concatenation 

### ISSUE THREAD

**Issue by Iambusayor** [owos/afri_augs#8]
Sentence concatenation, as explored in this paper ([Measuring the Impact of Data Augmentation Methods for Extremely Low-Resource NMT](https://aclanthology.org/2023.loresmt-1.8.pdf)), involves the random concatenation of multiple sentences with <SEP> as a separator token between concatenated sentences. Here, we need a class or script that performs the above for a given language pair. More information can be found in this paper [Sentence Concatenation Approach to Data Augmentation for Neural Machine Translation](https://aclanthology.org/2021.naacl-srw.18.pdf)

> e.g., let x represent english (en) sentences and y represent the yoruba (yor) translated sentences;
> 
> 
> x_1:  how are you my son.
> x_2:  the fuel in the lamp is about to finish.
> 
> 
> y_1: bawo ni omo mi. 
> y_2: epo ti o wa ninu fitila naa ti fẹrẹ pari.
> 
> 
> concatenated sentences
> x: how are you my son. <SEP> the fuel in the lamp is about to finish.
> y: the fuel in the lamp is about to finish. <SEP> epo ti o wa ninu fitila naa ti fẹrẹ pari.

**Comment by heisguyy** [comment]
I want this task.

**Comment by lumnolar** [comment]
can I work on this task with you?

**Comment by heisguyy** [comment]
I am almost done with it. It's just to implement the back translation that's left.
